import json
import os


class OpenMSXDebugScript:
    def generate(self, symbols_file, breakpoints, output_file=None):
        with open(symbols_file) as file:
            symbols = json.load(file)

        if output_file is None:
            output_file = os.path.splitext(symbols_file)[0] + '.tcl'

        functions = symbols.get('functions', {})
        lines = [
            '# Generated by ELiSE',
            '# Source: %s' % symbols.get('assembly', ''),
            '',
        ]
        seen = set()
        for function in breakpoints:
            if function in seen:
                continue
            seen.add(function)
            address = self._function_address(functions, function)
            lines.append(
                'debug breakpoint create %s' % address
            )

        with open(output_file, 'w') as file:
            file.write('\n'.join(lines) + '\n')
        return output_file

    def _function_address(self, functions, function):
        entry = functions.get(function)
        if entry is None:
            raise ValueError('Function not found in symbols: %s' % function)

        locations = entry.get('locations', [])
        if not locations:
            raise ValueError('No instruction locations for function: %s' % function)

        address = locations[0].get('address')
        if address is None:
            raise ValueError(
                'No assembled address for function: %s. '
                'Run with --assemble first.' % function
            )
        return address
